# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansChan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ransChan.proto\x12\x04main\"5\n\x03\x41ns\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"!\n\x07\x41nsList\x12\x16\n\x03\x61rr\x18\x01 \x03(\x0b\x32\t.main.Ans28\n\nAnsService\x12*\n\x0eProcessAnsList\x12\r.main.AnsList\x1a\t.main.AnsB\x06Z\x04./pbb\x06proto3')



_ANS = DESCRIPTOR.message_types_by_name['Ans']
_ANSLIST = DESCRIPTOR.message_types_by_name['AnsList']
Ans = _reflection.GeneratedProtocolMessageType('Ans', (_message.Message,), {
  'DESCRIPTOR' : _ANS,
  '__module__' : 'ansChan_pb2'
  # @@protoc_insertion_point(class_scope:main.Ans)
  })
_sym_db.RegisterMessage(Ans)

AnsList = _reflection.GeneratedProtocolMessageType('AnsList', (_message.Message,), {
  'DESCRIPTOR' : _ANSLIST,
  '__module__' : 'ansChan_pb2'
  # @@protoc_insertion_point(class_scope:main.AnsList)
  })
_sym_db.RegisterMessage(AnsList)

_ANSSERVICE = DESCRIPTOR.services_by_name['AnsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _ANS._serialized_start=23
  _ANS._serialized_end=76
  _ANSLIST._serialized_start=78
  _ANSLIST._serialized_end=111
  _ANSSERVICE._serialized_start=113
  _ANSSERVICE._serialized_end=169
# @@protoc_insertion_point(module_scope)
