// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: ansChan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ans struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author  string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Ans) Reset() {
	*x = Ans{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ansChan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ans) ProtoMessage() {}

func (x *Ans) ProtoReflect() protoreflect.Message {
	mi := &file_ansChan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ans.ProtoReflect.Descriptor instead.
func (*Ans) Descriptor() ([]byte, []int) {
	return file_ansChan_proto_rawDescGZIP(), []int{0}
}

func (x *Ans) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Ans) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ans) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arr []*Ans `protobuf:"bytes,1,rep,name=arr,proto3" json:"arr,omitempty"`
}

func (x *AnsList) Reset() {
	*x = AnsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ansChan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnsList) ProtoMessage() {}

func (x *AnsList) ProtoReflect() protoreflect.Message {
	mi := &file_ansChan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnsList.ProtoReflect.Descriptor instead.
func (*AnsList) Descriptor() ([]byte, []int) {
	return file_ansChan_proto_rawDescGZIP(), []int{1}
}

func (x *AnsList) GetArr() []*Ans {
	if x != nil {
		return x.Arr
	}
	return nil
}

var File_ansChan_proto protoreflect.FileDescriptor

var file_ansChan_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x6e, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x4d, 0x0a, 0x03, 0x41, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x07, 0x41, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x03, 0x61, 0x72, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x73, 0x52, 0x03, 0x61, 0x72, 0x72, 0x32, 0x38, 0x0a, 0x0a,
	0x41, 0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x41, 0x6e, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ansChan_proto_rawDescOnce sync.Once
	file_ansChan_proto_rawDescData = file_ansChan_proto_rawDesc
)

func file_ansChan_proto_rawDescGZIP() []byte {
	file_ansChan_proto_rawDescOnce.Do(func() {
		file_ansChan_proto_rawDescData = protoimpl.X.CompressGZIP(file_ansChan_proto_rawDescData)
	})
	return file_ansChan_proto_rawDescData
}

var file_ansChan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ansChan_proto_goTypes = []interface{}{
	(*Ans)(nil),     // 0: main.Ans
	(*AnsList)(nil), // 1: main.AnsList
}
var file_ansChan_proto_depIdxs = []int32{
	0, // 0: main.AnsList.arr:type_name -> main.Ans
	1, // 1: main.AnsService.ProcessAnsList:input_type -> main.AnsList
	0, // 2: main.AnsService.ProcessAnsList:output_type -> main.Ans
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ansChan_proto_init() }
func file_ansChan_proto_init() {
	if File_ansChan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ansChan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ans); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ansChan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ansChan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ansChan_proto_goTypes,
		DependencyIndexes: file_ansChan_proto_depIdxs,
		MessageInfos:      file_ansChan_proto_msgTypes,
	}.Build()
	File_ansChan_proto = out.File
	file_ansChan_proto_rawDesc = nil
	file_ansChan_proto_goTypes = nil
	file_ansChan_proto_depIdxs = nil
}
